use anyhow::{anyhow, Result};
use colored::*;
use std::env;
use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

pub fn install_git_hook() -> Result<()> {
    let cwd = env::current_dir()?;
    let git_dir = cwd.join(".git");

    if !git_dir.exists() {
        return Err(anyhow!("Current directory is not a Git repository. Run `git init` first."));
    }

    let hooks_dir = git_dir.join("hooks");
    if !hooks_dir.exists() {
        fs::create_dir_all(&hooks_dir)?;
    }

    let post_commit_path = hooks_dir.join("post-commit");

    let hook_script = r#"#!/bin/sh
# Auto-generated by agent-brain CLI
agent-brain handoff --auto > /dev/null 2>&1 &
"#;

    fs::write(&post_commit_path, hook_script)?;

    #[cfg(unix)]
    {
        let mut perms = fs::metadata(&post_commit_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&post_commit_path, perms)?;
    }

    println!("{}", "✨ Successfully installed agent-brain Git post-commit hook!".bold().green());
    println!("  📄 Hook Path: {}", post_commit_path.display().to_string().cyan());
    println!("{}", "💡 Now every `git commit` will automatically create a session handoff snapshot in the background!".bold().magenta());

    Ok(())
}

pub fn uninstall_git_hook() -> Result<()> {
    let cwd = env::current_dir()?;
    let post_commit_path = cwd.join(".git").join("hooks").join("post-commit");

    if post_commit_path.exists() {
        fs::remove_file(&post_commit_path)?;
        println!("{}", "✨ Successfully uninstalled agent-brain Git post-commit hook.".green());
    } else {
        println!("{}", "ℹ️ No Git post-commit hook found in current repository.".yellow());
    }

    Ok(())
}
