use anyhow::Result;
use colored::*;
use std::env;
use std::fs;
use crate::memory::MemoryManager;

pub fn sync_project_context() -> Result<()> {
    let memory_mgr = MemoryManager::new()?;
    let store = memory_mgr.load_store()?;

    let cwd = env::current_dir()?;
    let agents_md_path = cwd.join("AGENTS.md");
    let copilot_rules_path = cwd.join(".copilotrules");
    
    let github_dir = cwd.join(".github");
    if !github_dir.exists() {
        let _ = fs::create_dir_all(&github_dir);
    }
    let copilot_instructions_path = github_dir.join("copilot-instructions.md");

    let mut rules_content = String::new();
    rules_content.push_str("# Project Context & Agent Rules\n\n");
    rules_content.push_str("> Auto-generated by agent-brain CLI. Do not manually edit header.\n\n");

    rules_content.push_str("## 🧠 Developer Preferences & Code Conventions\n\n");
    if store.preferences.is_empty() {
        rules_content.push_str("- Follow clean code principles, modular architecture, and write self-documenting code.\n");
    } else {
        for pref in &store.preferences {
            rules_content.push_str(&format!("- {}\n", pref.content));
        }
    }

    rules_content.push_str("\n## 🛠️ Execution & Safety Guidelines\n");
    rules_content.push_str("- Always write clean, testable, and maintainable code.\n");
    rules_content.push_str("- Do not remove existing comments or tests unless explicitly requested.\n");

    // Write AGENTS.md
    fs::write(&agents_md_path, &rules_content)?;
    // Write .copilotrules
    fs::write(&copilot_rules_path, &rules_content)?;
    // Write .github/copilot-instructions.md (GitHub Copilot VS Code native format)
    fs::write(&copilot_instructions_path, &rules_content)?;

    println!("{}", "✨ Successfully synced memory & rules into project root:".bold().green());
    println!("  📄 {}", agents_md_path.to_string_lossy().cyan());
    println!("  📄 {}", copilot_rules_path.to_string_lossy().cyan());
    println!("  📄 {}", copilot_instructions_path.to_string_lossy().cyan());

    Ok(())
}
